services:
  https-reflector:
    image: https-reflector:latest
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/https-reflector:/data
      - /var/www/otto.stream:/var/www/public:ro
    env_file:
      - config.env
